import next from "@howells/lint/oxlint/next";
import { disabledReactDoctorRules } from "@howells/lint/oxlint/react-doctor-rules";

const legacyCompatibilityRules = {
  "class-methods-use-this": "off",
  complexity: "off",
  "default-case": "off",
  "func-names": "off",
  "func-style": "off",
  "import/first": "off",
  "import/no-duplicates": "off",
  "jsdoc/require-yields": "off",
  "max-classes-per-file": "off",
  "no-control-regex": "off",
  "no-duplicate-imports": "off",
  "no-empty-function": "off",
  "no-inline-comments": "off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-loop-func": "off",
  "no-plusplus": "off",
  "no-promise-executor-return": "off",
  "no-shadow": "off",
  "no-unused-vars": "off",
  "node/global-require": "off",
  "no-use-before-define": "off",
  "prefer-destructuring": "off",
  "promise/avoid-new": "off",
  "promise/prefer-await-to-callbacks": "off",
  "promise/prefer-await-to-then": "off",
  radix: "off",
  "require-await": "off",
  "require-unicode-regexp": "off",
  "sort-keys": "off",
  "typescript/ban-types": "off",
  "typescript/consistent-type-imports": "off",
  "typescript/no-explicit-any": "off",
  "typescript/no-extraneous-class": "off",
  "typescript/no-inferrable-types": "off",
  "typescript/no-invalid-void-type": "off",
  "typescript/no-non-null-assertion": "off",
  "typescript/no-unsafe-function-type": "off",
  "typescript/parameter-properties": "off",
  "unicorn/catch-error-name": "off",
  "unicorn/custom-error-definition": "off",
  "unicorn/filename-case": "off",
  "unicorn/no-array-for-each": "off",
  "unicorn/no-await-expression-member": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-static-only-class": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-string-slice": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/prefer-module": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-replace-all": "off",
};

export default {
  extends: [next],
  ignorePatterns: [".next/**", ".source/**", "node_modules/**", "out/**"],
  rules: {
    ...disabledReactDoctorRules,
    ...legacyCompatibilityRules,
  },
};
