import next from "@howells/lint/oxlint/next";
import { disabledReactDoctorRules } from "@howells/lint/oxlint/react-doctor-rules";

const legacyCompatibilityRules = {
  "class-methods-use-this": "off",
  complexity: "off",
  "default-case": "off",
  "func-names": "off",
  "func-style": "off",
  "import/first": "off",
  "import/no-duplicates": "off",
  "jsdoc/require-yields": "off",
  "max-classes-per-file": "off",
  "max-lines": "off",
  "max-lines-per-function": "off",
  "max-statements": "off",
  "no-control-regex": "off",
  "no-duplicate-imports": "off",
  "no-empty-function": "off",
  "no-inline-comments": "off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-loop-func": "off",
  "no-plusplus": "off",
  "no-promise-executor-return": "off",
  "no-restricted-properties": "off",
  "no-shadow": "off",
  "no-unused-vars": "off",
  "node/callback-return": "off",
  "node/global-require": "off",
  "no-use-before-define": "off",
  "prefer-arrow-callback": "off",
  "prefer-destructuring": "off",
  "prefer-named-capture-group": "off",
  "promise/avoid-new": "off",
  "promise/prefer-await-to-callbacks": "off",
  "promise/prefer-await-to-then": "off",
  radix: "off",
  "require-await": "off",
  "require-unicode-regexp": "off",
  "sort-keys": "off",
  "typescript/ban-types": "off",
  "typescript/consistent-type-imports": "off",
  "typescript/consistent-return": "off",
  "typescript/method-signature-style": "off",
  "typescript/no-base-to-string": "off",
  "typescript/no-deprecated": "off",
  "typescript/no-explicit-any": "off",
  "typescript/no-extraneous-class": "off",
  "typescript/no-floating-promises": "off",
  "typescript/no-inferrable-types": "off",
  "typescript/no-invalid-void-type": "off",
  "typescript/no-misused-promises": "off",
  "typescript/no-non-null-assertion": "off",
  "typescript/no-redundant-type-constituents": "off",
  "typescript/no-unnecessary-type-conversion": "off",
  "typescript/no-unnecessary-type-assertion": "off",
  "typescript/no-unnecessary-type-parameters": "off",
  "typescript/no-unsafe-argument": "off",
  "typescript/no-unsafe-assignment": "off",
  "typescript/no-unsafe-call": "off",
  "typescript/no-unsafe-function-type": "off",
  "typescript/no-unsafe-member-access": "off",
  "typescript/no-unsafe-return": "off",
  "typescript/no-unsafe-type-assertion": "off",
  "typescript/parameter-properties": "off",
  "typescript/prefer-nullish-coalescing": "off",
  "typescript/require-array-sort-compare": "off",
  "typescript/restrict-template-expressions": "off",
  "typescript/return-await": "off",
  "typescript/strict-boolean-expressions": "off",
  "typescript/strict-void-return": "off",
  "typescript/switch-exhaustiveness-check": "off",
  "typescript/use-unknown-in-catch-callback-variable": "off",
  "howells/no-runtime-dynamic-imports": "off",
  "unicorn/catch-error-name": "off",
  "unicorn/custom-error-definition": "off",
  "unicorn/filename-case": "off",
  "unicorn/import-style": "off",
  "unicorn/no-array-for-each": "off",
  "unicorn/no-await-expression-member": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-static-only-class": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-string-slice": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/prefer-module": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-replace-all": "off",
  "vitest/no-conditional-expect": "off",
  "vitest/valid-title": "off",
};

export default {
  extends: [next],
  ignorePatterns: [".next/**", ".source/**", "node_modules/**", "out/**"],
  rules: {
    ...disabledReactDoctorRules,
    ...legacyCompatibilityRules,
  },
};
